// NetView.idl : NetView的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(NetView.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(C7EF3768-03B8-4A7C-A085-6EEA75D488B5),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface INetViewDeskBand : IDispatch{
};
[
	uuid(B8321A6E-AC17-4004-8D3B-E65074F5EE15),
	version(1.0),
]
library NetViewLib
{
	importlib("stdole2.tlb");
	[
		uuid(2D1DD8A1-4C3E-4DBD-9E4D-ECBFE406B726)		
	]
	coclass NetViewDeskBand
	{
		[default] interface INetViewDeskBand;
	};
};

